[build]
builder = "dockerfile"
dockerfile = "./Dockerfile"

[[services]]
name = "web"
builder = "dockerfile"
dockerfile = "./Dockerfile"
startCommand = "python server.py 8088"
port = 8088
restartPolicyMaxRetries = 10

[[services]]
name = "logger"
builder = "dockerfile"
dockerfile = "./Dockerfile"
startCommand = "python logger.py --adaptive"
restartPolicyMaxRetries = 10

[env]
CARLINKO_DATA = "/data"
PORT = "8088"
PYTHONUNBUFFERABLE = "1"

[volumes]
data = "/data"
